/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.qidianai.bitmaker.event.EvQuote;
import com.qidianai.bitmaker.event.EvTest;
import com.qidianai.bitmaker.eventsys.Event;
import com.qidianai.bitmaker.eventsys.Reactor;
import com.qidianai.bitmaker.eventsys.Handler;
import org.junit.Test;

import java.util.concurrent.ConcurrentHashMap;


import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {
        App classUnderTest = new App();


        EvQuote q = new EvQuote();
        EvTest t = new EvTest();

        Long a = new Long(1L);
        Long b = new Long(1L);


        assertFalse(a == b);

        ConcurrentHashMap<Long, String> hashmap = new ConcurrentHashMap<>();
        hashmap.put(1L, "hi");

        assertTrue(hashmap.containsKey(1L));



    }

    @Test public void ReactorTest() throws InterruptedException {
        Handler handler = new Handler() {
            @Override
            public void handle(Event ev) {
                System.out.println(ev);
                System.out.println(ev.getData());
            }
        };

        EvQuote q = new EvQuote();
        EvTest t = new EvTest();

        q.setData(t);

        Reactor reactor = new Reactor();


        reactor.start();

        reactor.register(EvQuote.class, handler);
        reactor.register(EvTest.class, handler);


        reactor.publish(q);
        reactor.publish(t);

        Thread.sleep(1000);
        reactor.join();
    }
}
